FROM node:19

WORKDIR /app/

RUN npm install mocha@8.4.0 chai@4.3.4 --save-dev --save-exact \
  && npm install chai-http@4.3.0 --save-dev --save-exact \
  && npm install sinon@11.1.1 --save-dev --save-exact
